import type { Theme, ThemeName } from "./types.js";

export const themes: Record<ThemeName, Theme> = {
  "codex-ink": {
    name: "codex-ink",
    label: "Codex Ink",
    background: "#ffffff",
    foreground: "#202020",
    muted: "#707070",
    accent: "#e85d3f",
    link: "#e85d3f",
    listMarker: "#e85d3f",
    userBackground: "#0b0b0b",
    userForeground: "#ffffff",
    assistantBackground: "transparent",
    assistantForeground: "#202020",
    border: "#e0e0dc",
    codeBackground: "#f3f3f1",
    codeForeground: "#2a2a2a",
    frameBackground: "transparent",
    frameShadow: "none",
    frame: "none",
    layout: "native",
    tableStyle: "grid",
    fontFamily: "Geist, Noto Sans SC",
    bodyFontSize: 22,
    codeFontSize: 17,
    titleFont: "Noto Sans SC",
  },
  "warm-editorial": {
    name: "warm-editorial",
    label: "Warm Editorial",
    background: "#f6f1e7",
    foreground: "#332f2a",
    muted: "#7a7168",
    accent: "#b96142",
    link: "#b96142",
    listMarker: "#b96142",
    userBackground: "#2d2925",
    userForeground: "#fff9ef",
    assistantBackground: "transparent",
    assistantForeground: "#332f2a",
    border: "#d9cfbf",
    codeBackground: "#eae1d3",
    codeForeground: "#332f2a",
    frameBackground: "transparent",
    frameShadow: "none",
    frame: "none",
    layout: "native",
    tableStyle: "grid",
    fontFamily: "Geist, Noto Sans SC",
    bodyFontSize: 22,
    codeFontSize: 17,
    titleFont: "Source Serif 4",
  },
  "frosted-indigo": {
    name: "frosted-indigo",
    label: "Frosted Indigo",
    background: "#f4f6fb",
    foreground: "#252936",
    muted: "#70768a",
    accent: "#675ff2",
    link: "#675ff2",
    listMarker: "#675ff2",
    userBackground: "#252b46",
    userForeground: "#ffffff",
    assistantBackground: "transparent",
    assistantForeground: "#252936",
    border: "#d9deed",
    codeBackground: "#e8ebf5",
    codeForeground: "#252b46",
    frameBackground: "transparent",
    frameShadow: "none",
    frame: "none",
    layout: "native",
    tableStyle: "grid",
    fontFamily: "Geist, Noto Sans SC",
    bodyFontSize: 22,
    codeFontSize: 17,
    titleFont: "Noto Sans SC",
  },
  "raycast-night": {
    name: "raycast-night",
    label: "Raycast Night",
    background: "#151515",
    foreground: "#f4f4f1",
    muted: "#a1a19b",
    accent: "#ff6363",
    link: "#ff6363",
    listMarker: "#ff6363",
    userBackground: "#f1f0ec",
    userForeground: "#1b1b1a",
    assistantBackground: "transparent",
    assistantForeground: "#f4f4f1",
    border: "#323232",
    codeBackground: "#232323",
    codeForeground: "#f1f1ed",
    frameBackground: "transparent",
    frameShadow: "none",
    frame: "none",
    layout: "native",
    tableStyle: "grid",
    fontFamily: "Geist, Noto Sans SC",
    bodyFontSize: 22,
    codeFontSize: 17,
    titleFont: "Noto Sans SC",
  },
};

export function getTheme(name: string): Theme {
  const aliases: Record<string, ThemeName> = {
    "codex-native-light": "codex-ink",
    "codex-native-dark": "raycast-night",
    "agent-share-classic": "raycast-night",
    "paper-editorial": "warm-editorial",
    "paper-light": "warm-editorial",
    "gradient-window": "frosted-indigo",
    "transparent-material": "codex-ink",
    "codex-dark": "raycast-night",
  };
  const theme = themes[(aliases[name] ?? name) as ThemeName];
  if (!theme)
    throw new Error(
      `Unknown theme: ${name}. Choose ${Object.keys(themes).join(", ")}.`,
    );
  return theme;
}
